on:
  pull_request_target:
  push:
    branches-ignore:
      - "dependabot/**"

env:
  CI: true

jobs:
  init:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: ./cancel-redundant
        with:
          token: ${{ secrets.CANCEL_GITHUB_TOKEN }}

  # TODO: Get some tests running here
  # I guess we have already tested "cancel-redundant" above, I guess we just
  # execute the other actions as well? Gotta be careful of the whole pull_request
  # / pull_request_target vulnerabilities...
  # test:
  #   needs: init
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Git SHA
  #       id: gitRef
  #       run: |
  #         if [ "${{ github.event_name }}" == 'pull_request_target' ]; then
  #           echo "::set-output name=sha::${{ github.event.pull_request.head.sha }}"
  #         else
  #           echo "::set-output name=sha::${{ github.sha }}"
  #         fi
  #     - name: Checkout code
  #       uses: actions/checkout@v2.3.5
  #       with:
  #         ref: ${{ steps.gitRef.outputs.sha }}
  #     - name: Read .node-version
  #       run: echo ::set-output name=NODE_VERSION::$(cat .node-version | xargs)
  #       id: nvm
  #     - uses: actions/setup-node@v2.4.1
  #       with:
  #         node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
  #     - uses: pnpm/action-setup@v2.2.2
  #     - name: Restore node cache
  #       uses: actions/cache@v2.1.6
  #       with:
  #         path: ~/.pnpm-store
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: ${{ runner.os }}-node-

  release:
    if: "! contains(github.event_name, 'pull_request')"
    needs: init
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Read .node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .node-version | xargs)
        id: nvm
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.2.2
      - name: Restore node cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-
      - run: pnpm install
      - run: pnpx semantic-release
